var CACHE_MAX=8;var AE_F="Folder";var AE_AL="AddressList";var T_RCP="Recipients";var MA_PK="Pick";var MS_ABB="AddressBookBrowse";var MS_ABP="AddressBookPicker";var ID_DFTDOCM="ifDftDcMId";var g_rgsLFids=new Array();var g_sLstPFT=0;var g_fShwNMBtn=0;var g_fShwNVMBtn=0;var g_fShwNFBtn=0;var g_fShwRm=0;var g_oSnd=null;var g_sMId="";var g_sVMId="";var g_sFId="";var g_fAB=false;var g_iPllInt=0;var g_iPllPrdMs=0;var g_fNwMl=0;var g_fNwVMl=0;var g_fNwFx=0;var M_MAIL="Mail";var M_CAL="Calendar";var M_CTS="Contacts";var M_TSK="Tasks";var M_DOC="Documents";var M_PF="PublicFolders";var CONST_MS_IN_1MIN=60000;var g_nmDlg=250;var g_rmTmr=0;var g_rmDTmr=0;var OP_DIS=0;var OP_SNZ=1;var EXPND_HAS_RPLC="_fHasReplicaOfSameVrsn";var g_oPckMgr=new PckMgr();var g_fnSelCnt=null;var g_idCalsPrg=0;var g_sExpIco;var g_sClpsIco;var g_oOpnLocDlg=null;var g_oEdtLibSt=null;var g_oDocBtnSt=null;var g_fPLvLd=0;function chgAbLvSt(f){if(isPkr()){g_fPLvLd=f;disPkrBtns(!f);}}
function isAbPLvLd(){return (g_fPLvLd==1);}
function canDrg(){event.dataTransfer.dropEffect="none";canEvt();}
function onWL(){window.onunload=unload;g_iLgn=2;g_sExpIco=getThmF("expnd.gif");g_sClpsIco=getThmF("cllps.gif");document.onmousedown=rsStart;initSNLStls();g_fAB=isAB();if(!g_fAB){g_rgsLFids[NM_MAIL]=a_sInbx;g_rgsLFids[NM_CTS]=a_sCtcts;g_rgsLFids[NM_TSK]=a_sTsks;g_rgsLFids[NM_PF]=a_sPFrt;}if(g_fAB)initAB();switch(a_iNM){case NM_CAL:onNavCal();break;case NM_MAIL:onNavMail();break;case NM_AB:case NM_CTS:onNavCnt();break;case NM_TSK:onNavTsk();break;case NM_PF:onNavPF();break;}chgAbLvSt(1);if(g_fAB)return ;if(wda("divTo")){initRWFs(divTo,1,onFcsABRw,onFcsoutABRw,onKDABRw);divTo.ondragenter=canDrg;if(isDf(typeof (initHks))){initHks();document.onkeydown=chkHk;}setFcs(lnkAddrBk);}window.setTimeout(stPollN,30000);}
function unload(){if(isDf(typeof (dspAB))){dspAB();}else {dispRm();}window.oR=null;}
function initRWFs(div,fI,fnOnFcsIn,fnOnFcsOut,fnOnKD){if(div.scrollWidth>div.clientWidth)div.style.width=div.scrollWidth+4;initRw(div,fI,fnOnFcsIn,fnOnFcsOut,fnOnKD,1);div.fSp=1;div.fTi=1;div.zIdx=g_iDlgZ+2*g_iDlgZFct;}
function initHks(){addHk(L_HkRcps1,"checknames");addHk(L_HkRcps2,"checknames");var fn=onRwCmd;var iR=HKF_CMD|HKF_RW;addHk(L_HkCut,"cut",iR,fn);addHk(L_HkCpy,"copy",iR,fn);addHk(L_HkPst,"paste",iR,fn);addHk(L_HkUndo,"undo",iR,fn);addHk(L_HkRedo,"redo",iR,fn);}
function onRwCmd(sC,e){var oS=e.srcElement;if(isRW(oS))execCmdRw(oS,sC);}
function clkBtn(sC,oB){if(sC=="checknames"){var sId=event.srcElement.id;if(sId=="divTo")anrRcpFrm();else if(sId=="divOpnMbxRw")anrMbx();}}
function initSNDL(oL,fDsp){initSNL(oL,fDsp);var rg=items("divEnt",oL);for(var i=0;i<rg.length;i++){if(rg[i]._sel)oL.sel(rg[i]);}}
function isPkr(){return isDf(typeof (g_fABpkr))&&g_fABpkr;}
function onClkABFld(){if(wda("divCntFlds"))divCntFlds.unsel();var div=gtSNLEnt(event.srcElement);var sT=div._sT?div._sT:T_RCP;var oN=nvCtx();oN.fAB=1;oN.sAe=AE_AL;oN.sMa=isPkr()?MA_PK:null;nav(NM_AB,sT,div._fid,oN);}
function clkABmr(oDiv){var oD=wda("nABmr");var i=oDiv==oD[0]?1:0;var al=divAllAL;hideEm(oDiv);showEm(oD[i]);if(!i){hideEm(al);}else if(al.innerText!=""){showEm(al);}else {var oR=new oeReq("DB","AllAddressList",null,cballAB);oR.send();}}
function cballAB(oR){if(oR.sErr){if(oR.fST)popLgn();else shwErrDlg(oR);return ;}if(oR.sBody){divAllAL.innerHTML=oR.sBody;showEm(divAllAL);prepSNLEnts(divDirLst);}}
function onClkCntFld(){if(wda("divDirLst"))divDirLst.unsel();var div=gtSNLEnt(event.srcElement);var sFid=div._fid;var oN=nvCtx();if(g_fAB){oN.sMs=isPkr()?MS_ABP:MS_ABB;}g_rgsLFids[NM_CTS]=sFid;oN.fP=oN.fR=1;oN.fAB=g_fAB;oN.sFltr=divCntFlt.iCurFlt;nav(NM_CTS,T_CON,sFid,oN);}
function onClkCntF(){var oV=getLstVw(a_sLstFID);if(!oV)return ;var oF=gtSNFlt(event.srcElement);if(NM_PF==a_iNM||divCntFlds.oSel||divCntFlds.fDel){oV.iFltr=oF.iCurFlt;if(oV.rfrsh)oV.rfrsh();else oV.fNdRfrsh=1;}else {var oN=nvCtx();if(g_fAB)oN.sMs=isPkr()?MS_ABP:MS_ABB;oN.sFltr=oF.iCurFlt;oN.fP=oN.fR=oN.fAB=1;if(wda("divDirLst"))divDirLst.unsel();var rg=items("divEnt",divCntFlds);if(!rg.length)return ;divCntFlds.selFld(rg[0]._fid);nav(NM_CTS,T_CON,rg[0]._fid,oN);}}
function onNavCnt(){if(!wda("divCntFlds"))return ;initSNFL(divCntFlds);initSNFlt(divCntFlt);}
function onNavMail(){var oT=getTr(NM_MAIL);if(oT&&!oT.fTr){initTree(oT);hkTrEvt(oT);var o=trGtA(oT.childNodes[0]);o.attachEvent("onmouseover",gtAndShwMbxUsg);o.attachEvent("onmouseout",hdMbxUsg);}}
function hkTrEvt(oT){oT.onErr=onSNErr;oT.onSelNd=onTrSelNd;oT.onMvCpy=onSNMvCpy;oT.onMkAllRd=onTrMrkAllRd;oT.onBfMvFld=onTrBfMvFld;oT.onFldRnmed=onTrFldRnmed;oT.onFldCrted=onTrFldCrted;oT.onFldDlted=onTrFldDlted;oT.nav=nav;}
function window.document.oncontextmenu(){onEvtCanInpt();}
function window.document.onselectstart(){var oSrc=event.srcElement;if(oSrc.tagName=="DIV"){if(oSrc.id=="divTo"||oSrc.id=="divOpnMbxRw")return ;else canEvt();}}
function onTrSelNd(){var oT=getCrtTr();var sId=oT.gtSelNd();var oN=nvCtx();oN.fP=(sId==g_rgsLFids[NM_MAIL]||sId==a_sCal||sId==g_rgsLFids[NM_CTS]||sId==g_rgsLFids[NM_TSK]);oN.fR=(isDrty(sId)||sId==a_sLstFID);var sCC=oT.gtCntCls();var iM=NM_MAIL;if(oT.isPTr()){iM=NM_PF;if(isOfClss(sCC,T_CAL)){oN.fNoTdy=1;}else if(isOfClss(sCC,T_CON)){var oFlt=wda("divPFCntFlt");oN.sFltr=oFlt?oFlt.iCurFlt:0;oN.fR=1;}}else {if(isOfClss(sCC,T_CAL)){oN.cb=onNavCal;iM=NM_CAL;}else if(isOfClss(sCC,T_CON)){oN.cb=onNavCnt;oN.sFltr=wda("divCntFlt")?divCntFlt.iCurFlt:0;iM=NM_CTS;}else if(isOfClss(sCC,T_TSK)){oN.cb=onNavTsk;iM=NM_TSK;}}var sELCId=oT.gtSelELCNd();if(sELCId&&(sELCId!=sId))oN.sELCId=sELCId;else oN.sELCId=null;nav(iM,sCC,sId,oN);}
function onSNErr(oE){if(oE.iEC==440)rplLgn();else shwErrDlg(0,oE.sMsg);}
function onSNMvCpy(oE){if(oE.fC){if(a_sLstFID==oE.sDstFId){var oV=getLstVw(a_sLstFID);if(oV)oV.rfrsh();}else {rmvMd(oE.sDstFId);}}else {if(a_sLstFID==oE.sDstFId)return ;var oV=getLstVw(a_sLstFID);if(oV)oV.rmvItms(oE.rgIds);stDrty(oE.sDstFId);}}
function onTrMrkAllRd(oE){var sFId=oE.sFId;var oV=getLstVw(sFId);if(oV){var rgMIds=oV.gtAllItms();for(var i=0;i<rgMIds.length;++i)oV.mkRd(rgMIds[i]);oV.iUC=0;oV.feOnERfrsh();}}
function onTrBfMvFld(sId,sDId){if(a_sLstFID==sId){if(sDId){var oDst=getNd(this.gtAFrmItmId(sDId));if(oDst)selNd(oDst,1);else this.selNBNode(sId,1);}else {this.selNBNode(sId,1);}}else if(this!=getCrtTr()){var f=0;var iM;if(sId==g_rgsLFids[NM_MAIL]){f=1;iM=NM_MAIL;}else if(sId==g_rgsLFids[NM_PF]){f=1;iM=NM_PF;}if(!f)return ;var sIdSel=this.selNBNode(sId,0);g_rgsLFids[iM]=sIdSel;}}
function onTrFldRnmed(){setCSVAsStr(CSV_MRU_UPD_DT,new Date());setCSVAsStr(CSV_TR_UPD_DT,new Date());}
function onTrFldCrted(){setCSVAsStr(CSV_TR_UPD_DT,new Date());}
function onTrFldDlted(fP){if(fP)setCSVAsStr(CSV_MRU_UPD_DT,new Date());setCSVAsStr(CSV_TR_UPD_DT,new Date());}
function getPoMTr(fP){var iN=fP?NM_PF:NM_MAIL;return getTr(iN);}
function getTr(iNM){if(iNM==NM_MAIL||iNM==NM_PF){var oSN=getSN(iNM);if(oSN)return oSN.all[TR];}return 0;}
function getCrtTr(){return getTr(a_iNM);}
function tryFndTrNd(sFId){var oT=getPoMTr(isPFId(sFId));if(oT){var oA=oT.gtAFrmItmId(sFId);if(oA)return getNd(oA);}}
function getLstVw(sFId){var o=getIF(sFId);return (o?gtFrD(o).all.divLstV:null);}
function rmvMd(sFId){var o=getIF(sFId);if(o)o.removeNode();}
function getIF(sId){var o=tdVwr.all["b"+sId];if(o)gtFrD(o);return o;}
function getCW(sId){return getIF(sId).contentWindow;}
function getCDA(sId){return getCW(sId).document.all;}
function getCdaNB(){var o=null;var cda=getCDA(a_sLstFID);if(g_fShwNMBtn)o=cda["spnNwMl"];else if(g_fShwNVMBtn)o=cda["spnNwVMl"];else if(g_fShwNFBtn)o=cda["spnNwFx"];return o;}
function stDrty(id,f){var o=getIF(id);if(o)o._drty=!f;}
function isDrty(id,fl){var f=0;var o=getIF(id);var oMailTr=getTr(NM_MAIL);if(oMailTr){var oT=oMailTr.gtAFrmItmId(id);if(oT)f=oT._nc;}return (o?(o._drty||(f&&!fl)):0);}
function updCnt(id,tc,uc){var oMailTr=getTr(NM_MAIL);if(oMailTr)oMailTr.updCnts(id,tc,uc);}
function setPllInt(pllPrdMs){if(pllPrdMs!=g_iPllPrdMs){if(g_iPllInt){window.clearInterval(g_iPllInt);g_iPllInt=0;}g_iPllPrdMs=pllPrdMs;g_iPllInt=window.setInterval(pollN,pllPrdMs);}}
function stPollN(){if(isFtEnab(FT_NOTIF)){pollN();setPllInt(a_iNtInt);}}
function pollN(){if(g_iRC)return ;var oR=new oeReq("Notify","Poll",null,cbPoll,null,null,0,1);var oRDlg=rmGtRDlg();if(oRDlg&&oRDlg.lstRT)oR.add("LRT",new Date(oRDlg.lstRT));oR.send();}
function cbPoll(oR){try{if(oR.sErr){if(oR.fST)rplLgn();else shwNE(1,oR);}else {shwNE(0,0);if(oR.sBody!=""){eval(oR.sBody);if(isDrty(a_sLstFID,1)){var oCW=getCW(a_sLstFID);if(oCW){if(oCW.refresh){oCW.refresh();}}}window.oR=oR;return true;}}}catch(e){if(!isAccDnd(e.message))throw e;}}
function rmNotfy(iOff,fR,sRT,sHTML,sErr){var oRDlg=rmInitDlg();if(!oRDlg)return ;oRDlg.offset=iOff;if(fR){oRDlg.iNwOff=0;oRDlg.lstRT=sRT;var dtClntNw=oRDlg.rmUtcNw();var dtSvrNw=new Date(sRT);oRDlg.iNwOff=dtSvrNw-dtClntNw;oRDlg.all["divRDI"].innerHTML=oRDlg.rmInit(sHTML);}if(sErr)oRDlg.shwErr(sErr);else oRDlg.shwErr("");oRDlg.rmStTm();oRDlg.rmUdB();if(!oRDlg.rmItms().length){if(oRDlg.isOpn)oRDlg.oDlg.hide();return ;}if(oRDlg.isOpn)oRDlg.rmSelF(0);if(fR){if(!oRDlg.isOpn)oRDlg.rmShw(0,1);if(oRDlg.sn)plySnd();}}
function shwNB(f,bId,sId,fId){if(!fId)fId=a_sLstFID;var oB=getCDA(fId)[bId];var oS=getCDA(fId)[sId];if(oB&&oS){showEm(oB,!f);showEm(oS,!f);}}
function shwNM(f,fId){g_fShwNMBtn=f;shwNB(f,"spnNwMl","sepNwMl",fId);}
function shwNVM(f,fId){g_fShwNVMBtn=f;shwNB(f,"spnNwVMl","sepNwVMl",fId);}
function shwNF(f,fId){g_fShwNFBtn=f;shwNB(f,"spnNwFx","sepNwFx",fId);}
function shwNE(f,oR){var o=getIF(a_sLstFID);if(o){o=o.contentWindow.setNEI;if(o){o(oR);shwNB(f,"spnNE","sepNE");}}}
shwNwItmDlg.oT=0;function shwNwItmDlg(sFrm,sSbj,sTyp,sIcnPth){var cda=getCDA(a_sLstFID);var o=cda[sTyp];if(o){clsNDlg(0);if(shwNwItmDlg.oT)window.clearTimeout(shwNwItmDlg.oT);var oRDlg=rmGtRDlg();if(!oRDlg||!oRDlg.isOpn){var nmDlg=new NwItmDlg("idNewItmDlg",sFrm,sSbj,sIcnPth);var oLnk=o.all["lnkNB"];var iX=getNBX(o)+3-g_nmDlg;var iY=getNBY(o)+2;nmDlg.show(iX,iY);aplNBStl(1,oLnk);shwNwItmDlg.oT=window.setTimeout("clsNDlg(1);",5000);}else {shwNwItmDlg.oT=window.setTimeout("hideInbxNB();",5000);}window.setTimeout("updCmp('"+window+"')",5001);}}
function hideInbxNB(){if(!g_fAB&&a_sLstFID==a_sInbx){if(g_fShwNMBtn==1)shwNM(0);if(g_fShwNVMBtn==1)shwNVM(0);if(g_fShwNFBtn==1)shwNF(0);}}
function clsNDlg(f){var o=getCdaNB();if(o)aplNBStl(0,o.all["lnkNB"]);var oDiv=wtda("idNewItmDlg");if(oDiv&&oDiv.oDlg){if((typeof (f)=="undefined")||f)hideInbxNB();oDiv.oDlg.hide();}}
function NwItmDlg(sId,sFrm,sSbj,sIcnPth){var sOppDir=g_fRtl?"left":"right";var sHtml="<div id=idNMDlg class=btnNMDlg style=width:"+g_nmDlg+";><table id=idNMTbl><tr><td id=idNMImg><img src=\""+sIcnPth+"\"></td><td id=idFrm>"+sFrm+"</td></tr><tr><td></td><td id=idSbjct>"+sSbj+"</td></tr></table>"+"</div><div class=graybox style=text-align:"+sOppDir+"></div>";var oDlg=new Dlg(sId,sHtml,1,0,clsNDlg);var oDiv=wtda(sId);oDiv.all["idNMDlg"].onclick=new Function("clkNDlg(wtda(\""+oDiv.uniqueID+"\").oDlg);");return oDlg;}
function clkNDlg(oDlg){var o=getCdaNB();if(o){aplNBStl(0,o.all["lnkNB"]);setTimeout("dsplyVw(\""+o.id+"\")",1);}oDlg.hide();}
function dsplyVw(sId){var sMId;switch(sId){case "spnNwMl":shwNM(0);if(g_sMId)sMId=g_sMId;g_fNwMl=1;break;case "spnNwVMl":shwNVM(0);if(g_sVMId)sMId=g_sVMId;g_fNwVMl=1;break;case "spnNwFx":shwNF(0);if(g_sFId)sMId=g_sFId;g_fNwFx=1;break;}if(a_sLstFID==a_sInbx){divLstV=getLstVw(a_sInbx);getCW(a_sLstFID).clrFnd();if(sMId){var oA=divLstV.gtAFrmItmId(sMId);if(oA&&sMId==getCW(a_sInbx).getRPmid())divLstV.selItmById(sMId);else divLstV.seekItm(sMId);}else {divLstV.rfrsh();}}else {var oN=nvCtx();oN.fR=isDrty(a_sInbx);oN.mId=sMId;oN.cb=onNavMail;nav(NM_MAIL,T_MSG,a_sInbx,oN);}}
function gtNavX(){return (isDisp(tblNb)?tblNb.offsetWidth:tblMb.offsetWidth);}
function getNBX(o){var iX=getCX(o);iX+=gtNavX();iX+=o.offsetWidth;return iX;}
function rmGtNBX(o,oDlg){var iX=getCX(o);if(!g_fRtl){iX=Math.max(iX+o.offsetWidth-oDlg.offsetWidth,0);iX+=gtNavX();iX+=3;}return adjPos(iX,oDlg,ADJ_L);}
function getNBY(o){return logo.clientHeight+o.parentElement.clientHeight;}
var g_sUrlSnd=0;function plySnd(){if(!wtda("tmSnd2")){if(!g_sUrlSnd)g_sUrlSnd=getThmF("notify.wav");g_oSnd=document.body.insertBefore(document.createElement("BGSOUND"),null);g_oSnd.id="tmSnd2";g_oSnd.src=g_sUrlSnd;g_oSnd.LOOP=1;}g_oSnd.src=g_oSnd.src;}
function navMail(){var oN=nvCtx();oN.fP=1;oN.fR=isDrty(g_rgsLFids[NM_MAIL]);oN.cb=onNavMail;nav(NM_MAIL,T_MSG,g_rgsLFids[NM_MAIL],oN);}
function navCal(){var oN=nvCtx();oN.fP=1;oN.fR=isDrty(a_sCal);oN.cb=onNavCal;nav(NM_CAL,T_CAL,a_sCal,oN);}
function navCtcts(){var oN=nvCtx();oN.fP=1;oN.fR=isDrty(a_sCtcts);oN.cb=onNavCnt;oN.sFltr=wda("divCntFlt")?divCntFlt.iCurFlt:null;nav(NM_CTS,T_CON,a_sCtcts,oN);}
function navTsks(){var oN=nvCtx();oN.fP=1;oN.fR=isDrty(a_sTsks);oN.cb=onNavTsk;nav(NM_TSK,T_TSK,a_sTsks,oN);}
function navDocs(){nav(NM_DOC,T_DOC,(g_rgsLFids[NM_DOC]?g_rgsLFids[NM_DOC]:ID_DFTDOCM),0);}
function navPFs(){if(a_fLegPF){sfWinOpn("/public/");return ;}if(""==a_sPFrt){var oR=new oeReq("Tree","GetRootPublicFolderId",0,cbGetPFRtId);oR.send();return ;}else if(0==g_rgsLFids[NM_PF]){g_rgsLFids[NM_PF]=a_sPFrt;}var oN=nvCtx();oN.fP=1;oN.fR=isDrty(g_rgsLFids[NM_PF]);oN.cb=onNavPF;nav(NM_PF,g_sLstPFT?g_sLstPFT:T_MSG,g_rgsLFids[NM_PF],oN);}
function cbGetPFRtId(oR){if(!cbOeh(oR))return ;a_sPFrt=oR.sBody;navPFs();}
function navOpts(){var rg=new Array();rg[NM_MAIL]="Messaging";rg[NM_CAL]="Calendar";rg[NM_CTS]="General";rg[NM_TSK]="Calendar";rg[NM_DOC]="Messaging";rg[NM_PF]="Messaging";document.location.href="?ae=Options&opturl="+rg[a_iNM];event.returnValue=false;}
function isPrmNvT(sT){return sT!=null&&(sT==T_MSG||sT==T_CAL||sT==T_CON||sT==T_TSK||sT==T_DOC);}
function nvCtx(){this.sAe=AE_F;this.fP=this.fR=this.mId=this.fNoTdy=this.oC=this.fAB=this.sMa=this.sMs=this.sFltr=this.cb=this.sPrntFdrUri=null;return this;}
function nav(iM,sT,sId,oN){if(!oN)oN=nvCtx();var fAB=oN.fAB;if(!fAB)selNbBtn(iM);hideEm(getIF(a_sLstFID));try{getCW(a_sLstFID).unselect();}catch(e){}if(tdSecNv.children){for(var j=0;j<tdSecNv.children.length;j++)hideEm(tdSecNv.children[j]);}if(!fAB)tdMdNm.innerText=getLMN(iM);loadVw(sT,sId,oN);if(!fAB&&isDisp(tblNb)){loadSecNv(iM,sId,oN.cb);}if(iM!=NM_CAL)g_rgsLFids[iM]=sId;a_sLstFID=sId;a_iNM=iM;if(iM==NM_PF)g_sLstPFT=sT;var oMbQt=wda("mbqt");if((oMbQt!=null)&&(oMbQt._dsp==1)){if(iM!=NM_MAIL)hideEm(oMbQt);else showEm(oMbQt);}}
function dsplyNwMB(fId){shwNM(g_fShwNMBtn,fId);shwNVM(g_fShwNVMBtn,fId);shwNF(g_fShwNFBtn,fId);}
function loadVw(sT,sId,oN){var sSrc="?ae="+oN.sAe+"&t=";var sMac=oN.sMa?"&a="+oN.sMa:"";var sMst=oN.sMs?"&s="+oN.sMs:"";hideInbxNB();var oIF=getIF(sId);if(oIF){var oCW=getCW(sId);try{var oD=oCW.document;}catch(e){rn(oIF);oIF=0;}}if(oIF){showEm(oIF);dsplyNwMB(sId);var oRDlg=rmGtRDlg();if(oRDlg&&oRDlg.fInit&&oRDlg.isOpn)oRDlg.oDlg.hide();var oMDlg=gtMbxDlg();if(oMDlg&&oMDlg.fInit)oMDlg.oDlg.hide();rmUdB(oD.all.spnRm,sId);try{oCW.select(oN);}catch(e){}}else {if(tdVwr.children.length>=CACHE_MAX){var o=tdVwr.children[0];while(o&&getInt(o._cF))o=o.nextSibling;if(o){var id=o.id;if(id&&(id.charAt(0)=="b")){id=id.substring(1);}if(id!=a_sInbx){var oR=new oeReq("Notify","DeleteCA",null,null,null,null,0,1);oR.add("sId",id);oR.send();}o.removeNode(1);}}chgAbLvSt(0);var o=getEm("IFRAME");o.id="b"+sId;o.className="wh100";o.frameBorder=0;o.src=sSrc+sT+sMac+sMst;o._cF=oN.fP?1:0;o._drty=0;if(oN.sFltr)o.src=o.src+"&fltr="+oN.sFltr;if(oN.sPrntFdrUri)o.src=o.src+oN.sPrntFdrUri;if(sId)o.src+=((sT!=T_DOC)?"&id=":"&URL=")+urlEnc(sId);if((sT==T_DOC)&&oN.oC)o.src+=oN.oC;if(oN.sELCId&&isAllwdELCClss(sT))o.src+="&elcId="+urlEnc(oN.sELCId);tdVwr.appendChild(o);}}
function regNotfs(){rmUdB();dsplyNwMB();if(g_fShwRm){window.setTimeout(rmPending,5000);g_fShwRm=0;}}
function rmPending(){var oRDlg=rmGtRDlg();if(oRDlg&&oRDlg.fInit)oRDlg.rmShw(0,1);}
function getSN(iM){return tdSecNv.children[getMN(iM)];}
function getCrtSNDiv(){return getSNDiv(a_iNM);}
function getSNDiv(iM){var div=0;if(iM==NM_MAIL||iM==NM_PF)div=getTr(iM);else if(iM==NM_CTS)div=isDf(typeof (divCntFlds))?divCntFlds:0;else if(iM==NM_CAL)div=isDf(typeof (divCalFlds))?divCalFlds:0;else if(iM==NM_TSK)div=isDf(typeof (divTskFlds))?divTskFlds:0;return div;}
function loadSecNv(iM,sId,fnOnNav){var sMId=getMN(iM);if(tdSecNv.children[sMId]){showEm(tdSecNv.children[sMId]);var div=getSNDiv(iM);if(!div)return ;if((iM==NM_MAIL||iM==NM_PF)&&div.selNodeById)div.selNodeById(sId);else if(div.selFld)div.selFld(sId);if(iM==NM_PF)shwPFFlt();}else {var o=getEm("DIV");o.id=sMId;o.className="wh100";tdSecNv.appendChild(o);var oCtx=new Object();oCtx.iM=iM;oCtx.sId=sId;oCtx.fnOnNav=fnOnNav;var oR=sv("GetSecondaryNavigation","m",iM,oCtx,cbReqSecNv,1);oR.add("fId",sId);oR.send();}}
function cbReqSecNv(oR){if(oR.sErr){if(oR.fST)rplLgn();else shwErrDlg(oR);}else {getSN(oR.oCtx.iM).innerHTML=oR.sBody;var fnOnNav=oR.oCtx.fnOnNav;if(fnOnNav)fnOnNav();var div=getSNDiv(oR.oCtx.iM);if(!div)return ;if(oR.oCtx.iM==NM_MAIL||oR.oCtx.iM==NM_PF)div.selNodeById(oR.oCtx.sId);else div.selFld(oR.oCtx.sId);}}
function getMd(sT){switch(sT){case T_MSG:return NM_MAIL;case T_CAL:return NM_CAL;case T_CON:return NM_CTS;case T_TSK:return NM_TSK;case T_DOC:return NM_DOC;default:return NM_MAIL;}}
function getMN(iM){var rg=new Array();rg[NM_MAIL]=M_MAIL;rg[NM_CAL]=M_CAL;rg[NM_CTS]=M_CTS;rg[NM_TSK]=M_TSK;rg[NM_AB]="";rg[NM_DOC]=M_DOC;rg[NM_PF]=M_PF;return rg[iM];}
function getLMN(iM){var o=null;switch(iM){case NM_MAIL:o=lnkInbx;break;case NM_CAL:o=lnkCal;break;case NM_CTS:o=lnkCtcts;break;case NM_TSK:o=lnkTsks;break;case NM_DOC:o=lnkDocs;break;case NM_PF:o=lnkPFs;break;default:o=lnkInbx;break;}return o.innerText.trim();}
function tglMnBr(){var f=isDisp(tblNb);if(f){showEm(tblMb);hideEm(tblNb);}else {hideEm(tblMb);showEm(tblNb);}tdNv.width=f?tblMb.offsetWidth:a_iNW;imgRR.style.cursor=f?"default":"col-resize";var oR=sv("PersistMiniBar","m",f?1:0,null,cbSv);oR.send();var fn=null;switch(a_iNM){case NM_CAL:fn=onNavCal;break;case NM_MAIL:fn=onNavMail;break;case NM_CTS:fn=onNavCnt;break;case NM_TSK:fn=onNavTsk;break;case NM_PF:fn=onNavPF;break;}var oSN=getSN(a_iNM);if(!oSN)loadSecNv(a_iNM,a_sLstFID,fn);else showEm(oSN);}
function tglNvMnu(){var f=isDisp(trNbMax);if(f){showEm(trNbMin);hideEm(trNbMax);}else {hideEm(trNbMin);showEm(trNbMax);}var oR=sv("PersistQuickLinksBar","q",f?1:0,null,cbSv);oR.send();}
function selNbBtn(iM){if(iM==a_iNM)return ;var rg=new Array();rg[NM_MAIL]="Inbx";rg[NM_CAL]="Cal";rg[NM_CTS]="Ctcts";rg[NM_TSK]="Tsks";rg[NM_DOC]="Docs";rg[NM_PF]="PFs";var s="nbHiLt";var o=document.all;o["lnk"+rg[a_iNM]].className="";o["lnkQl"+rg[a_iNM]].className="";o["lnkMb"+rg[a_iNM]].className="";o["divTx"+rg[a_iNM]].className="nbTx";o["lnk"+rg[iM]].className=s;o["lnkQl"+rg[iM]].className=s;o["lnkMb"+rg[iM]].className=s;o["divTx"+rg[iM]].className=s+"Tx";}
function sv(sE,sP,oV,sC,fn,fGet){var oR=new oeReq("Navigation",sE,sC,fn,fGet?GET:POST);oR.add(sP,oV);return oR;}
function cbSv(oR){if(oR.fST)rplLgn();}
function setNbW(iW,fSave){var iMW=document.body.clientWidth-g_iMinRPW;if(iW>iMW)iW=iMW;if(iW<g_iMinVWW)iW=g_iMinVWW;if(fSave&&a_iNW!=iW){a_iNW=iW;var oR=sv("PersistWidth","w",iW,null,cbSv);oR.send();}tdNv.width=iW;}
function emptyFldr(sId,fPF){var fDI=a_sDlItms==sId;var fIsJnk=0;if((!fDI)&&(a_sJnk==sId))fIsJnk=1;var sDlgMsg;var sDlgTtl;if(fPF){sDlgMsg=L_PrEmpPF;sDlgTtl=L_EmptDltFdrTtl;}else if(fDI){sDlgMsg=L_WrnEmpt;sDlgTtl=L_EmptFdrTtl;}else if(fIsJnk){sDlgMsg=L_WrnEmptJnk;sDlgTtl=L_EmptJnk;}else {sDlgMsg=L_WrnEmptFldr;sDlgTtl=L_EmptDltFdrTtl;}var oCtx=new Object();oCtx.fDI=fDI;oCtx.fIsJnk=fIsJnk;oCtx.sId=sId;var oD=new BtnDlg("divDlt",sDlgMsg,sDlgTtl,new Array("OK","Cancel"),null,null,onDltFdr,null,null,null,null,null,oCtx);oD.show();}
function onDltFdr(i,oCtx){if(i==0){var sMthd;if(oCtx.fDI)sMthd="EmptyDeletedItems";else if(oCtx.fIsJnk)sMthd="EmptyJunkEmail";else sMthd="EmptyFolder";var oR=new oeReq("Tree",sMthd,oCtx,cbEmptyFldr);if(!oCtx.fDI&&!oCtx.fIsJnk)oR.add("id",oCtx.sId);oR.send();}}
function cbEmptyFldr(oR){if(oR.sErr){if(oR.fST)rplLgn();else shwErrDlg(oR);return ;}var oCtx=oR.oCtx;if(oCtx.fDI)getTr(NM_MAIL).clearNode(a_sDlItms);else if(oCtx.fIsJnk)getTr(NM_MAIL).clearNode(a_sJnk);if(a_sLstFID==oCtx.sId){var oLV=getLstVw(oCtx.sId);if(oLV&&oLV.rfrsh)oLV.rfrsh();}else {var oDF;if(oCtx.fDI)oDF=getIF(a_sDlItms);else if(oCtx.fIsJnk)oDF=getIF(a_sJnk);if(oDF)oDF.removeNode();}if((oCtx.fDI)||(oCtx.fIsJnk))getTr(NM_MAIL).gtMbxUsg();}
function cmfFPOnClkBtn(sId,sNm,sT,oC){var oT=getCrtTr();var fC=oC.fC;var o=new DrgCtx("folder",oT.gtSelNd());var oCtx=new Object();oCtx.oDC=o;oCtx.fC=fC;oCtx.sDstFId=sId;oCtx.oSN=oT;var oR=gtCpMvReq(o,fC,sId,oCtx,cbDrpF,0);oR.send();}
function initSnDp(sId,fnOnDtChg,fnOnErr,fnOnNavM){var oDp=new DatePicker(wda(sId),fnOnDtChg);oDp.onErr=fnOnErr;oDp.onAfNv=fnOnNavM;var o=getIF(a_sLstFID);if(o){if(!oDp.fFBLd){getFB(oDp,a_sLstFID,fnOnErr);oDp.fFBLd=1;}}return oDp;}
function initSnMp(sId,fnOnMChg){return new MonthPicker(wda(sId),fnOnMChg);}
function onErrSnDp(oDivErr,oR,fErr){if(fErr)showErr(oDivErr,oR.sErr,oR.sErrDbg);else hideErr(oDivErr);}
function onSnDtChg(){var rgDts=g_oPckMgr.getSelDts();g_oPckMgr.iMode=g_oPckMgr.getDp().iMode;var o=getIF(a_sLstFID);if(o){o=o.contentWindow.setVw;if(o)o(rgDts,g_oPckMgr.iMode);}}
function onNavCal(){if(!wda("divCalFlds"))return ;g_oPckMgr.setPck(initSnDp("dp",onSnDtChg,onErrCalDP,onCalDpNavM),initSnMp("divMp",onSnDtChg),0);initSNFL(divCalFlds);}
function onClkCalFld(){var div=gtSNLEnt(event.srcElement);var sFid=div._fid;var oN=nvCtx();oN.fP=oN.fNoTdy=1;oN.fR=0;oN.cb=onNavCal;nav(NM_CAL,T_CAL,sFid,oN);}
function onErrCalDP(oR,fErr){onErrSnDp(divErrDP,oR,fErr);}
function onCalDpNavM(oDp){getFB(oDp,a_sLstFID,onErrCalDP);}
function onNavTsk(){if(!wda("divTskFlds"))return ;initSNFL(divTskFlds);initSNFlt(divTskFlt);updTskFlt();}
function onClkTskFld(){var sFid=gtSNLEnt(event.srcElement)._fid;g_sLstTFld=sFid;var oN=nvCtx();oN.fP=oN.fR=1;nav(NM_TSK,T_TSK,sFid,oN);updTskFlt();}
function updTskFlt(sFId){sFId=sFId?sFId:a_sLstFID;var oV=getLstVw(sFId);if(!oV)return ;var o=isPFId(sFId)?divPFTskFlt:divTskFlt;o.setFlt(oV.iFltr);}
function onClkTskFlt(){var oV=getLstVw(a_sLstFID);if(!oV||!oV.rfrsh)return ;oV.iFltr=gtSNFlt(event.srcElement).iCurFlt;oV.rfrsh();}
function onNavPF(){var oT=getTr(NM_PF);if(oT&&!oT.fTr){initTree(oT);hkTrEvt(oT);shwPFFlt();}}
var g_rgfFltLd=new Array();function shwPFFlt(){var oTr=getTr(NM_PF);var sT=oTr.gtCntCls();var sFId=oTr.gtSelNd();var iHasRplc=oTr.gtNdPrpt(sFId,EXPND_HAS_RPLC);if(!isDf(typeof (iHasRplc))){var o=new Object();o.sT=sT;o.sFId=sFId;var oR=new oeReq("Tree","GetPublicFolderReplicaType",o,cbGetPfRt);oR.add("id",sFId);oR.send();return ;}var sId=getPfFltId(sT);if(sId==0||!iHasRplc){shwPFFDiv(1);return ;}var o=wda(sId);if(o){shwPFFDiv(0,sT);if(isOfClss(sT,T_TSK))updTskFlt(sFId);}else {var oCtx=new Object();oCtx.sT=sT;oCtx.sFId=sFId;var oR=sv("GetPFFilter","t",sT,oCtx,cbGetPFFlt,1);if(isOfClss(sT,T_CAL))oR.add("fId",sFId);oR.send();}}
function cbGetPfRt(oR){if(!oehSccd(oR)){return ;}eval(oR.sBody);var oT=getTr(NM_PF);oT.stNdPrpt(oR.oCtx.sFId,EXPND_HAS_RPLC,iHasRplc);shwPFFlt();}
function cbGetPFFlt(oR){if(!cbOeh(oR)){shwPFFDiv(1);return ;}var sT=oR.oCtx.sT;if(!g_rgfFltLd[sT]){var oDiv=getEm("div");ac(oDiv);oDiv.innerHTML=oR.sBody;var o=oDiv.children[0];var oP=wda("tdPFFlt");ibe(oP,o);rn(oDiv);g_rgfFltLd[sT]=1;if(isOfClss(sT,T_CON)||isOfClss(sT,T_TSK))initSNFlt(o);else if(isOfClss(sT,T_CAL))g_oPckMgr.setPck(initSnDp("divPfDp",onSnDtChg,onErrPfDP,onPfDpNavM),initSnMp("divPfMp",onSnDtChg),1);hideEm(o);shwPFFlt();}}
function shwPFFDiv(fH,sT){if(!fH)shwPFFDiv(!fH);var oP=wda("tdPFFlt");showEm(oP,fH);if(oP.children){for(var i=0;i<oP.children.length;i++)hideEm(oP.children[i]);}if(sT){showEm(wda(getPfFltId(sT)),fH);}showEm(wda("tdPFPd"),fH);}
function getPfFltId(sT){if(isOfClss(sT,T_CON))return "divPFCntFlt";else if(isOfClss(sT,T_TSK))return "divPFTskFlt";else if(isOfClss(sT,T_CAL))return "divPFCalFlt";return 0;}
function onErrPfDP(oR,fErr){onErrSnDp(divErrPfDp,oR,fErr);}
function onPfDpNavM(oDp){getFB(oDp,a_sLstFID,onErrPfDP);}
function tbA(sC,oC){switch(sC){case "emptydeleted":emptyFldr(a_sDlItms);break;case "emptyjunk":emptyFldr(a_sJnk);break;case "openlocdl":opnLoc();break;case "opendl":nav(NM_DOC,T_DOC,(oC.length?oC[0]:divDfm.docLib.uri));break;case "opennewdl":sfWinOpn(DLF_URI+urlEnc(oC.length?oC[0]:divDfm.docLib.uri));break;case "deletedl":delLib();break;case "renamedl":edtLib();break;default:var oT=getCrtTr();if(!(oT&&oT.hasSelNode()))return ;switch(sC){case "open":onTrSelNd();break;case "opennew":opnNew(oT.gtSelNd(),oT.gtCntCls(),oT.gtSelELCNd());break;case "delete":var fPD=oT.isPTr()?1:event.ctrlKey;oT.deleteNode(oT.gtSelNd(),a_sDlItms,fPD);break;case "rename":nwFld(oT,0);break;case "createfolder":nwFld(oT,1);break;case "markread":oT.markAllRead(oT.gtSelNd());break;case "emptyfldr":emptyFldr(oT.gtSelNd(),oT.isPTr());break;case "movefolder":var oC=new Object();oC.fC=0;var oA=new Object();oA.sBtn=L_Mv;oA.sTtl=L_MvToFld;shwFPDlg(oA,cmfFPOnClkBtn,oC);break;case "copyfolder":var oC=new Object();oC.fC=1;var oA=new Object();oA.sBtn=L_Cp;oA.sTtl=L_CpToFld;shwFPDlg(oA,cmfFPOnClkBtn,oC);break;case "createMailFld":nwFld(oT,1,T_MSG);break;case "createCalFld":nwFld(oT,1,T_CAL);break;case "createCntFld":nwFld(oT,1,T_CON);break;case "createTskFld":nwFld(oT,1,T_TSK);break;case "createNtsFld":nwFld(oT,1,T_NTS);break;}}}
function opnNew(sId,sT,sELCId){sUrl="?ae=Folder&t="+urlEnc(sT)+"&id="+urlEnc(sId);if(sELCId&&(sELCId!=sId)&&isAllwdELCClss(sT))sUrl+="&elcId="+urlEnc(sELCId);sfWinOpn(sUrl);}
function opnLoc(){var oS=divOpnLoc.currentStyle;var y=getCY(divOpnLoc)+divOpnLoc.offsetHeight-parseInt(oS.paddingBottom)-2;g_oOpnLocDlg=new OpnLocDlg(onOpnLocCls);g_oOpnLocDlg.show((g_fRtl?(getCX(divOpnLoc)-divOpnLoc.offsetWidth-30):0),y);txtOpnLoc.onselectstart=allowEvt;txtOpnLoc.select();divOpnLoc.style.backgroundColor=getDocBtnSt().backgroundColor;divOpnLoc.style.borderColor=getDocBtnSt().borderColor;divOpnLoc.style.color=getDocBtnSt().color;}
function getDocBtnSt(){if(g_oDocBtnSt==null)g_oDocBtnSt=getStyle("docBtn");return g_oDocBtnSt;}
function onOpnLocCls(){divOpnLoc.style.backgroundColor="";divOpnLoc.style.borderColor="";}
function OpnLocDlg(fnCls){var sOppDir=g_fRtl?"left":"right";var sHtml="<div id=divOpnLocDlg onkeydown=kdOpnLoc()><div class=titlebox>"+"<img class=btn onclick=g_oOpnLocDlg.hide() style=float:"+sOppDir+" src=\""+getThmF("closedlg.gif")+"\">"+divOpnLoc.L_OpnLoc+"</div><div class=mainbox><div class=graybox><div>"+divOpnLoc.L_OpnLocDesc+"</div><input type=text id=txtOpnLoc></div><div class=whitebox><div id=divOpnPrg><img align=absmiddle src=\""+getThmF("pgrs-sm.gif")+"\">&nbsp;&nbsp;"+divOpnLoc.L_Opning+"</div><div id=divOpnBtn style=\"text-align:"+sOppDir+"\"><button id=btnOpnLoc onclick=\"clkOpnLoc()\" onmouseover=\"btnOnMsOvrBtn(this)\" onmouseout=\"btnOnMsOutBtn(this)\">"+divOpnLoc.L_Opn+"</button></div></div></div></div>";return new Dlg("divOpnDocLib",sHtml,0,1,fnCls,0,0);}
function clkOpnLoc(){var sU=txtOpnLoc.value.trim();txtOpnLoc.value=sU;if(sU.length==0){setFcs(txtOpnLoc);return ;}var f=(btnOpnLoc.innerText==divOpnLoc.L_Opn);divOpnPrg.style.visibility=f?"visible":"";txtOpnLoc.disabled=f;btnOpnLoc.innerText=f?divOpnLoc.L_Cncl:divOpnLoc.L_Opn;if(!f)txtOpnLoc.select();else clsLnk(sU);}
function clsLnk(sU){var oR=new oeReq("DocumentLibrary","ClassifyLink",sU,cbClsLnk);oR.add("uri",sU);oR.send();}
function cbClsLnk(oR){if((typeof (wda("divOpnLocDlg"))=="undefined")||(btnOpnLoc.innerText==divOpnLoc.L_Opn))return ;if(oR.sErr){if(oR.fST){rplLgn();}else {clkOpnLoc();alrt(L_InvUri);}return ;}var oD=getEm("DIV");ac(oD);oD.innerHTML=oR.sBody;if(oD.all.err){clkOpnLoc();var okDlg=new BtnDlg("idOkDlg",htmlEnc(oD.all.err._msg),htmlEnc(oD.all.err._ttl),new Array(divOpnLoc.L_OK),null,parseInt(oD.all.err._icn),opnDlgOnCls,divOpnDocLib);okDlg.show();return ;}var sU=oD.all.uri.innerText;var iUF=parseInt(oD.all.uf.innerText);var sId=oD.all.oid.innerText;var iFWR=oD.all.divFwr.innerText;rn(oD);if(iFWR==1)opnWebRFrm(sU,iUF);else opnDocItm(sU,iUF,sId);g_oOpnLocDlg.hide();}
function opnDlgOnCls(){txtOpnLoc.select();}
function kdOpnLoc(){if(event.keyCode==13)clkOpnLoc();else if(event.keyCode==27)g_oOpnLocDlg.hide();allowEvt();}
function edtLib(){var o=divDfm.docLib;var oS=getDocLibSpn(o);var oT=document.createElement("INPUT");oT.type="text";oT.value=oS.innerText;oT.onselectstart=allowEvt;oT.onkeydown=onKDLib;oT.maxLength=255;iae(oS,oT);hideEm(oS);if(g_oEdtLibSt==null)g_oEdtLibSt=getStyle("edtBox");oT.style.borderWidth=g_oEdtLibSt.borderWidth;oT.style.borderColor=g_oEdtLibSt.borderColor;oT.style.borderStyle=g_oEdtLibSt.borderStyle;var oC=new Object();oC.spn=oS;oC.txt=oT;oC.docLib=divDfm.docLib;oT.oC=oC;oT.select();oT.onfocusout=renLib;oT.oncontextmenu=canEvt;oT.onclick=canEvt;}
function allowEvt(){event.returnValue=true;event.cancelBubble=true;}
function onKDLib(){var oE=event;var oT=oE.srcElement;if(oE.keyCode==13)oT.blur();else if(oE.keyCode==27)rstrLib(oT.oC);allowEvt();}
function renLib(){var sV=event.srcElement.value;var oC=event.srcElement.oC;if((sV.length==0)||(sV==oC.spn.innerText)){rstrLib(oC);return ;}var oR=new oeReq("DocumentLibrary","RenFav",oC,cbRenLib);oR.add("uri",oC.docLib.uri);oR.add("dn",sV);oR.send();}
function cbRenLib(oR){if(oR.sErr){if(oR.fST)rplLgn();return ;}var oC=oR.oCtx;oC.spn.innerText=oC.txt.value;var sT=oC.docLib.title;oC.docLib.title=oC.txt.value+"\n"+sT.substring(sT.indexOf("\n")+1);rstrLib(oC);}
function rstrLib(oC){oC.txt.removeNode(1);showEm(oC.spn);oC.docLib.style.backgroundColor="";}
function delLib(){var oR=new oeReq("DocumentLibrary","DelFav",divDfm.docLib,cbDelLib);oR.add("uri",divDfm.docLib.uri);oR.send();}
function cbDelLib(oR){if(oR.sErr){if(oR.fST)rplLgn();return ;}rn(oR.oCtx);}
function isDispOF(){return isDisp(wda("divFavFldrs"));}
function tglDocBlk(sId){var o=wda("div"+sId);var oTr=wda("tr"+sId);if(!isDisp(o)){if(o.children.length==0){var oCtx=new Object();oCtx.sId=sId;var oR=new oeReq("DocumentLibrary","Get"+sId,oCtx,cbGetBlk);oR.send();}else {oTr.style.height="100%";showEm(o);wda("img"+sId).src=g_sClpsIco;svDocBlkSt(sId,1);}}else {hideEm(o);wda("img"+sId).src=g_sExpIco;oTr.style.height="100%";svDocBlkSt(sId,0);}}
function cbGetBlk(oR){if(oR.sErr){if(oR.fST)rplLgn();}else {var sId=oR.oCtx.sId;var oTr=wda("tr"+sId);var o=wda("div"+sId);oTr.style.height="100%";showEm(o);wda("img"+sId).src=g_sClpsIco;o.innerHTML=oR.sBody;}}
function svDocBlkSt(sId,iV){var oR=new oeReq("DocumentLibrary","Persist"+sId,null,cbSv);oR.add("fV",iV);oR.send();}
function shwDocMnu(o,fF){if(!divDfm.show)CtxMnu(divDfm,tbA);showEms(new Array(divDfmD,divDfmR),!fF);divDfmD._lnk=divDfmR._lnk=fF?1:0;divDfm.docLib=o;divDfm.show(event);}
function getDocLibSpn(o){return o.children[1].children[0];}
function rmSelF(fF){var rg=this.rmItms();if(!rg.length)return ;this.rmUnsA(rg);this.rmS(rg[0],1,fF);}
function rmItms(){var j=0;var rg=new Array();for(var i=0;i<this.divRDI.children.length;i++){var rm=this.divRDI.children[i];if((rm._lnk==1)&&(isDisp(rm)))rg[j++]=rm;}return rg;}
function rmAItms(){var j=0;var rg=new Array();for(var i=0;i<this.divRDI.children.length;i++){var rm=this.divRDI.children[i];if(rm._lnk==1)rg[j++]=rm;}return rg;}
var g_sClearIco=null;function rmUdH(rgS){var rI=rS=rD=rL=rId=0;if(!g_sClearIco)g_sClearIco=getThmF("clear.gif");if(rgS.length==1){var o=rgS[0];if(divRB._uI==o.uniqueID)return ;rI=o.all["imgR"].src;rS=o.all["divS"].innerHTML;rD=o.getAttribute("tf");rL=o.getAttribute("l");rId=o.uniqueID;}else if(rgS.length){rS=this.sr;}this.divRB.all["imgRH"].src=rI?rI:g_sClearIco;this.divRB.all["divRHS"].innerHTML=rS?rS:"";this.divRB.all["divRHD"].innerText=rD?rD:"";this.divRB.all["divRHL"].innerText=rL?rL:"";this.divRB._uI=rId;}
function rmFnd(o){if(!this.divRDI.contains(o))return 0;while(o){if(o._lnk)return o;o=o.parentElement;}return 0;}
function rmGtS(){var rg=this.rmItms();var rgS=new Array();for(var i=0;i<rg.length;i++){if(rg[i]._sel==1)rgS.push(rg[i]);}return rgS;}
function rmUnsA(){var rg=this.rmItms();for(var i=0;i<rg.length;i++){this.rmS(rg[i],0);}}
function rmStS(o,f){if(!g_ocmS)cmStyle();o.style.backgroundColor=f?g_ocmS.bgC:"";o.style.borderColor=f?g_ocmS.bdrC:"";}
function rmS(o,f,fF){rmStS(o,f);o._sel=f;var rgS=this.rmGtS();this.rmUdH(rgS);this.rmSnzOpts(rgS);this.rmEnB(rgS.length);if(f&&fF)setFcs(o);}
function rmNxtSel(o,rg){if(rg.length==1)return ;for(var i=0;i<rg.length;i++){if(rg[i].uniqueID==o.uniqueID)return (i==rg.length-1)?rg[i-1]:rg[i+1];}}
function onMDRm(){var o=this.rmFnd(event.srcElement);if(!o)return ;if(event.ctrlKey){if(o._sel)this.rmS(o,0);else this.rmS(o,1);}else {this.rmUnsA();this.rmS(o,1,1);}}
function procRm(iOp,sC,rgS,sRT,iT){if(g_iRC)return ;var oC=new Object();oC.iOp=iOp;oC.rgS=rgS;var oR=new oeReq("RemindersEventHandler",sC,oC,cbProcRm);if(iT)oR.add("Snt",iT);if(sRT)oR.add("LRT",new Date(sRT));var rg=rmGtRS(oR,rgS);if(!rg||!rg.length)return ;oR.addRgSt("Rm",rg);oR.send();}
function cbProcRm(oR){if(oR.sErr){if(oR.fST)popLgn();else shwErrDlg(oR);}else {var oC=oR.oCtx;var iOp=oC.iOp;var rgS=oC.rgS;var oRDlg=rmInitDlg();if(iOp==OP_SNZ){eval("oRDlg.rmRmv(rgS, iOp,"+oR.sBody+");");}else {oRDlg.rmRmv(rgS,iOp);}if((oRDlg.rmItms().length<1)&&oRDlg.isOpn){oRDlg.oDlg.hide();}else if(oRDlg.isOpn){var o=oRDlg.rmItms()[0];if(oRDlg.nxtSel)o=oRDlg.nxtSel;oRDlg.rmS(o,1,1);}}}
function rmShwErr(s){this.all["divRmErrT"].innerText=s;showEm(this.all["divRmErr"],!s);}
function rmToStrc(oRI,oR){var oRS=new oeSt(oR,"rmInfo");oRS.add("id",oRI.id);oRS.add("ck",oRI.ck);return oRS;}
function RmInfo(o){this.id=o.getAttribute("id");this.ck=o.getAttribute("ck");}
function rmGtRS(oR,rgS){var rg=new Array();for(var i=0;i<rgS.length;i++){var o=rgS[i];var oRm=new RmInfo(o);rg.push(rmToStrc(oRm,oR));}return rg;}
function Rrsp(sCk,sRnt,fD){this.ck=sCk;this.r=sRnt;this.fD=fD?1:0;}
function rmRmv(rgR,iOp,rgU){if(!iOp)iOp=OP_DIS;var iL=rgR.length-1;for(var i=0;i<rgR.length;++i){if(i==iL)this.nxtSel=rmNxtSel(rgR[i],this.rmItms());var fD=rgU&&rgU[i].fD;this.rmRmvI(rgR[i],iOp,fD);if(rgU&&!fD){rgR[i].ck=rgU[i].ck;rgR[i].r=rgU[i].r;}}this.rmStTm();this.rmUdB();}
function rmRmvI(o,iOp,fD){if(this.oNxtRm==o)rmClrTm();if(iOp==OP_DIS||fD){o.removeNode(1);}else {hideEm(o);this.rmS(o,0);}}
function rmClrDTm(){if(g_rmDTmr){wt().clearInterval(g_rmDTmr);g_rmDTmr=0;}}
function rmClrTm(){if(g_rmTmr){wt().clearTimeout(g_rmTmr);g_rmTmr=0;}}
function rmStTm(){rmClrTm();this.rmStRNT();}
function rmStDTm(){rmClrDTm();g_rmDTmr=wt().setInterval(rmUdD,30000);}
function rmUdD(){var oRDlg=rmGtRDlg();if(!oRDlg)return ;if(oRDlg.isOpn==1)oRDlg.rmRfsh();}
var SOUND_ONLY=1;var SHOW_DIALOG=2;function rmStRNT(){var rg=this.rmAItms();var nowUTC=this.rmUtcNw();var maxY=4501;var nextRm=0;var fShw=0;var oW=wt();for(var i=0;i<rg.length;i++){var o=rg[i];var rnt=new Date(o.r);var dueBy=new Date(o.t);if(rnt.getYear()==maxY)continue;if(nowUTC<rnt){nextRm=o;o._sel=0;hideEm(o);}else {if(!isDisp(o)){if(nowUTC<dueBy&&!o.fired)rmShwEm(o,this);else showEm(o);}}}if(nextRm){this.RNT=new Date(nextRm.r);g_rmTmr=oW.setTimeout(rmFire,this.RNT-nowUTC);}this.oNxtRm=nextRm;}
function rmShwEm(o,oRDlg){oRDlg.rmS(o,1,1);o.all["divDRm"].innerHTML=oRDlg.rmUdDS(o);showEm(o);this.rmUdB();if(!oRDlg.isOpn)oRDlg.rmShw(0,1);if(oRDlg.sn)plySnd();o.fired=1;}
function rmFire(){g_rmTmr=null;var oRDlg=rmGtRDlg();if(!oRDlg||!oRDlg.fInit)return ;var oRm=oRDlg.oNxtRm;rmShwEm(oRm,oRDlg);oRDlg.rmStTm();}
function onClkRmd(sC){if(!sC)sC=event.srcElement.id;if(sC==this.id)sC=this.cmd;var rgS=this.rmGtS();if(!rgS.length&&sC!="selectall")return ;switch(sC){case "snooze":procRm(OP_SNZ,"Snooze",rgS,this.lstRT,this.oCmb.getV());break;case "dismiss":procRm(OP_DIS,"Dismiss",rgS,this.lstRT);break;case "dismissall":procRm(OP_DIS,"Dismiss",this.rmItms());break;case "open":rmOpn(rgS);break;case "selectall":var rg=this.rmItms();this.rmUnsA();for(var i=0;i<rg.length;i++)this.rmS(rg[i],1);}canEvt();}
function onDClkRm(){var o=this.rmFnd(event.srcElement);if(!o)return ;rmOpn(new Array(o));}
function rmOpn(rgS){for(var i=0;i<rgS.length;i++){var sAe="Item";var t=rgS[i].c;if(isCal(t))sAe="PreFormAction";var sUrl="?ae="+sAe;sUrl+="&a=Open";sUrl+="&t="+urlEnc(t);var id=rgS[i].id;if(rgS[i].oid)id=rgS[i].oid;sUrl+="&id="+urlEnc(id);openItm(sUrl);}}
function rmRfsh(f){var rg=this.rmItms();if(!rg.length)return ;var dt=this.rmUtcNw();var dtR=this.dtRfrsh;var nDiff=dt-this.dtRfrsh;if(nDiff>=20000||f){for(var i=0;i<rg.length;i++){rg[i].all["divDRm"].innerHTML=this.rmUdDS(rg[i]);}this.dtRfrsh=dt;}}
function rmInit(sHTML){var oW=wt();var oD=getEm("DIV",oW.document);oW.document.body.appendChild(oD);hideEm(oD);oD.innerHTML=sHTML;if(!oD.children.length)return "";for(var i=0;i<oD.children.length;i++){var o=oD.children[i];o.all["divDRm"].innerHTML=this.rmUdDS(o);}var sS=oD.innerHTML;oD.removeNode(1);return sS;}
function rmCls(){var oRDlg=rmGtRDlg();oRDlg.isOpn=0;rmClrDTm();rmStB(0);var oSlct=oRDlg.oCmb.oSlct;if(oSlct.isOpn)oSlct.cls();if(oRDlg.rmItms().length)rmTglDD(0);}
function rmStB(f){var oB=rmGtB(a_sLstFID);if(!oB)return ;var oA=oB.all["lnkRm"];aplNBStl(f,oA);}
function aplNBStl(f,oLnk){if(!g_oDef)initBtnStls();if(f&&!oLnk._pushed)aplStl(oLnk,g_oDwn);else if(!f&&oLnk._pushed)aplStl(oLnk,g_oDef);oLnk._pushed=f;}
function rmTglDD(f,oB){if(!oB)oB=rmGtB();if(!oB)return ;var oImg=oB.all["imgRm"];if(oImg._d==f)return ;if(f){oImg.src=getThmF("up-arrw.gif");oImg.style.marginTop=1;}else {oImg.src=getThmF("dwn.gif");oImg.style.marginTop=4;}oImg._d=f;}
function rmAdjBtns(oRD){var rgBtns=oRD.getElementsByTagName("BUTTON");for(var i=0;i<rgBtns.length;++i){var iW=gow(rgBtns[i]);if(100<iW)spw(rgBtns[i],(iW*0.8));}oRD.adjB=1;}
function rmShw(fFc,fR){if(!this.rmItms().length||this.isOpn)return ;var oB=rmGtB();if(!oB){g_fShwRm=1;return ;}this.rmRfsh(fR);this.rmStDTm();this.rmSelF(fFc);rmStB(1);if(!isDisp(this)){spt(this,-5000);spl(this,-5000);showEm(this);}rmTglDD(1,oB);if(!this.adjB)rmAdjBtns(this);var iX=rmGtNBX(oB,this);var iY=getNBY(oB);this.oDlg.show(iX,iY+2);this.isOpn=1;}
function onKDRm(){var rg=this.rmItms();var iIdx=cmSelIdx(rg);var fSel=(iIdx!=-1);var e=event;var o=event.srcElement;if(this.hkSelA.iHash==cmptHash(e.ctrlKey?1:0,e.altKey?1:0,e.shiftKey?1:0,e.keyCode)){this.cmd="selectall";this.click();canEvt();return ;}switch(event.keyCode){case 27:this.oDlg.hide();break;case 9:var oS=this.rmFnd(o);if(oS){dismissall.focus();}else if((o.id=="snooze"&&!event.shiftKey)||(o.id=="dismissall"&&event.shiftKey)){if(fSel)setFcs(rg[iIdx]);else this.rmS(rg[0],1,1);}else {return ;}break;case 13:if(o==this.oCmb.imgDrp)return ;this.onclick("open");break;case 40:if(iIdx==(rg.length-1))break;if(fSel){this.rmS(rg[iIdx],0);this.rmS(rg[iIdx+1],1,1);}else {this.rmS(rg[0],1);}break;case 38:if(fSel&&(iIdx!=0)){this.rmS(rg[iIdx],0);this.rmS(rg[iIdx-1],1,1);}break;case 35:if(iIdx==(rg.length-1))break;if(fSel)this.rmS(rg[iIdx],0);this.rmS(rg[rg.length-1],1,1);break;case 36:if(iIdx==0)break;;if(fSel)this.rmS(rg[iIdx],0);this.rmS(rg[0],1,1);break;default:return ;}canEvt();}
function rmUdDS(o){var dtNow=this.rmUtcNw();var dtDue=new Date(o.t);var sDue="";var sS="";var iM=(dtDue-dtNow)/CONST_MS_IN_1MIN;if(0<iM){iM=Math.floor(iM);sDue=this.d;}else {iM=Math.ceil(iM);iM=-iM;sDue=this.od;}if(iM==0){return this.n;}else {var rgD=new Array(4);rgD[3]=rgD[2]=rgD[1]=0;rgD[0]=Math.floor(iM/(7*24*60));if(2>rgD[0]){rgD[1]=Math.floor(iM/(24*60))%7;if(2>rgD[1]&&0==rgD[0]){rgD[2]=Math.floor(iM/60)%24;if(8>=rgD[2]&&0==rgD[1])rgD[3]=Math.floor(iM)%60;}}var f=1;var u=0;for(var i=0;i<4;i++,u+=3){var s="";if(0!=rgD[i]){if(!f)sDue+=" ";else f=0;s=this.rmTU(rgD[i],u);}sDue=sDue.replace(this.reu[i],s);}}return sDue;}
function rmTU(iV,iU){var re1=new RegExp(this.re1,"gi");var re2=new RegExp(this.re2,"gi");var idx=(re1.test(iV))?0:re2.test(iV)?1:2;return (this.u[iU+idx].replace(/\%1/,iV));}
function rmUtcNw(){var browserNow=new Date();var clientNow=new Date();var browserTZoffset=browserNow.getTimezoneOffset();var browserUTCNow=new Date(Date.UTC(browserNow.getFullYear(),browserNow.getMonth(),browserNow.getDate(),browserNow.getHours(),browserNow.getMinutes(),browserNow.getSeconds()));clientNow.setTime(browserUTCNow.getTime()+((browserTZoffset+this.offset)*60000)+this.iNwOff);return clientNow;}
function rmGtB(sFId){if(!sFId)sFId=a_sLstFID;try{return (getIF(sFId).contentWindow.document.all.spnRm);}catch(e){return 0;}}
function rmUdB(oB,sId){var iCnt=0;if(!oB)var oB=rmGtB();if(!oB)return ;var oRDlg=rmGtRDlg();if(oRDlg&&oRDlg.fInit){var rg=oRDlg.rmItms();iCnt=(rg&&rg.length)?rg.length:0;oB.all["spnRmT"].innerHTML=oRDlg.fs.replace("%1",iCnt);}var isVis=isDisp(oB);if(!sId)sId=a_sLstFID;var oD=getCW(sId).document.all["sepRm"];if(!iCnt&&isVis){hideEm(oB);hideEm(oD);}else if(iCnt&&!isVis){showEm(oB);showEm(oD);rmTglDD(oRDlg.isOpn,oB);}}
function dispRm(){if(g_rmTmr)rmClrTm();if(g_rmDTmr)rmClrDTm();var oB=rmGtB();if(oB)initHBtns(new Array(oB),0);var oRDlg=rmGtRDlg();if(!oRDlg)return ;oRDlg.oncontextmenu=oRDlg.onkeydown=oRDlg.onmousedown=oRDlg.ondblclick=null;initHBtns(new Array(dismissall,dismiss,wda("open"),snooze),0);if(tblSnzT.oSlct)dispSlct(tblSnzT);}
function rmInitDlg(){var oRDlg=rmGtRDlg();if(!oRDlg)return 0;if(oRDlg.fInit)return oRDlg;var oDlg=new Dlg("divRmd",0,1,0,rmCls,0,1,0,1);var dtMin="01-01-1582 00:00:00 UTC";Slct(tblSnzT);oRDlg.lstRT=0;oRDlg.RNT=0;oRDlg.oNxtRm=0;oRDlg.isOpn=0;oRDlg.dtRfrsh=new Date(dtMin);oRDlg.u=oRDlg.u.split(",");oRDlg.reu=new Array(/\%1/g,/\%2/g,/\%3/g,/\%4/g);oRDlg.oCmb=tblSnzT;oRDlg.divRDI=divRDI;oRDlg.divRB=divRB;oRDlg.selIdx=0;oRDlg.oncontextmenu=new Function("return(0)");oRDlg.onkeydown=onKDRm;oRDlg.onmousedown=onMDRm;oRDlg.onclick=onClkRmd;oRDlg.ondblclick=onDClkRm;oRDlg.shwErr=rmShwErr;oRDlg.rmSelF=rmSelF;oRDlg.rmItms=rmItms;oRDlg.rmAItms=rmAItms;oRDlg.rmUdH=rmUdH;oRDlg.rmFnd=rmFnd;oRDlg.rmGtS=rmGtS;oRDlg.rmUnsA=rmUnsA;oRDlg.rmS=rmS;oRDlg.rmRmv=rmRmv;oRDlg.rmRmvI=rmRmvI;oRDlg.rmClrTm=rmClrTm;oRDlg.rmStTm=rmStTm;oRDlg.rmClrDTm=rmClrDTm;oRDlg.rmStDTm=rmStDTm;oRDlg.rmStRNT=rmStRNT;oRDlg.rmFire=rmFire;oRDlg.rmUdB=rmUdB;oRDlg.rmRfsh=rmRfsh;oRDlg.rmCls=rmCls;oRDlg.rmShw=rmShw;oRDlg.rmUdDS=rmUdDS;oRDlg.rmTU=rmTU;oRDlg.rmUtcNw=rmUtcNw;oRDlg.rmSnzOpts=rmSnzOpts;oRDlg.rmSnzL=rmBfS(tblSnzT.oSlct);oRDlg.rmInit=rmInit;oRDlg.hkSelA=new hk(L_HkSel,"selectall",0,0);oRDlg.fInit=1;oRDlg.rmEnB=rmEnB;oRDlg.iNwOff=0;oRDlg.sn=getInt(oRDlg.sn);oRDlg.oDlg=oDlg;return oRDlg;}
function rmBfS(oS){var rg=new Array();for(var i=0;i<4;++i){rg.push(oS.children[i]);}return rg;}
function rmSnzOpts(rgS){var rgL=this.rmSnzL;var now=this.rmUtcNw();var fSt=0;var dtS=0;var iL=rgS.length;if(iL==1){var o=rgS[0];dtS=new Date(o.t);if((dtS>now)&&isCal(o.c))fSt=1;}var oCmb=this.oCmb;var oV=oCmb.oSlct.oV;if(fSt){var iM=Math.round((dtS-now)/CONST_MS_IN_1MIN);rgL[0].style.display=(iM>15)?"":"none";rgL[1].style.display=(iM>10)?"":"none";rgL[2].style.display=(iM>5)?"":"none";rgL[3].style.display="";oV=(iM>5)?-5:0;}else {for(var i=0;i<this.rmSnzL.length;++i){hideEm(rgL[i]);}}if(oV!=null)oCmb.setV(oV);var fE=(iL>0)?1:0;this.oCmb.enbl(fE);}
function rmEnB(f){var rgB=this.getElementsByTagName("BUTTON");for(var i=0;i<rgB.length;i++){var o=rgB[i];o.style.cursor=f?"hand":"default";o.disabled=!f;}}
function initSNL(oL,fDsp){prepSNLEnts(oL,fDsp);oL.oSel=null;oL.sel=snlSelEnt;oL.unsel=snlUnsel;}
function prepSNLEnts(oL,fDsp){var rg=items("divEnt",oL);for(var i=0;i<rg.length;i++){rg[i].onmouseover=fDsp?null:onMOvrSNL;rg[i].onmouseout=fDsp?null:onMOutSNL;rg[i].onclick=fDsp?null:onClkSNL;rg[i].title=rg[i].innerText;}}
function snlSelEnt(o){if(this.oSel!=o){aplSNLStl(o,SNLStl.sel);if(this.oSel)aplSNLStl(this.oSel,SNLStl.def);this.oSel=o;}}
function snlUnsel(){if(this.oSel)aplSNLStl(this.oSel,SNLStl.def);this.oSel=0;}
function onMOvrSNL(){var o=gtSNLEnt(event.srcElement);var oL=gtSNL(o);if(oL.oSel!=o)aplSNLStl(o,SNLStl.hvr);}
function onMOutSNL(){var o=gtSNLEnt(event.srcElement);var oL=gtSNL(o);if(oL.oSel!=o)aplSNLStl(o,SNLStl.def);}
function onClkSNL(){var o=gtSNLEnt(event.srcElement);var oL=gtSNL(o);oL.sel(o);eval(o._onclick);}
function gtSNLEnt(o){return srchPr("divEnt",o);}
function gtSNL(o){while(o&&!o.fSNL)o=o.parentElement;return o;}
function SNLStl(o,sC){o.className=sC;var oS=o.currentStyle;this.bgC=oS.backgroundColor;this.bdrC=oS.borderColor;this.c=oS.color;}
function initSNLStls(){var o=getEm("a");ibe(document.body,o);SNLStl.def=new SNLStl(o,"snlDef");SNLStl.sel=new SNLStl(o,"snlSel");SNLStl.hvr=new SNLStl(o,"snlHvr");document.body.removeChild(o);}
function aplSNLStl(oB,oS){if(!oS)return ;var oBS=oB.style;oBS.backgroundColor=oS.bgC;oBS.borderColor=oS.bdrC;oBS.color=oS.c;}
function initSNFL(oL){initSNL(oL);oL.getFld=snflGetFld;oL.selFld=snflSelFld;oL.selCur=snflSelCur;oL.feOnErr=snflFeOnErr;oL.onMvCpy=onSNMvCpy;oL.ondragover=onDOSNFL;oL.ondragenter=onDOSNFL;oL.ondragleave=onDLSNFL;oL.ondrop=onDrpSNFL;oL.selCur();}
function snflSelCur(){var o=getIF(a_sLstFID);if(o){o=o.contentWindow.a_sFId;if(o)this.selFld(o);}}
function snflSelFld(sFId){var o=this.getFld(sFId);if(o){this.sel(o);this.fDel=0;}else {this.unsel();this.fDel=1;}}
function snflGetFld(sFId){var rg=items("divEnt",this);for(var i=0;i<rg.length;i++){if(rg[i]._fid==sFId)return rg[i];}}
function onClkFldN(){var oL=gtSNL(event.srcElement);oL.all.txtFldN.onfocusout=onFOFldN;shwFldN(oL,1);setFcs(oL.all.txtFldN);}
function shwFldN(oL,f){oL.all.txtFldN.value="";showEm(oL.all.tblFldN,!f);showEm(oL.all.divFldN,f);}
function onFOFldN(){var oL=gtSNL(event.srcElement);if(oL.all.txtFldN.value.trim().length==0){cnFldN(oL);return ;}creatFld(oL);}
function cnFldN(oL){if(!oL)oL=gtSNL(event.srcElement);if(oL.idCalsPrg)return ;oL.all.txtFldN.onfocusout=null;shwFldN(oL,0);hideErr(oL.all.divFldErr);}
function onKDFldN(){var oL=gtSNL(event.srcElement);switch(event.keyCode){case 13:creatFld(oL);break;case 27:cnFldN();break;}allowEvt();}
function creatFld(oL){oL.all.txtFldN.onfocusout=null;shwFldPrg(oL);var oR=new oeReq("Navigation","CreateFolder",oL,cbCreatFld,POST);oR.add("fN",oL.all.txtFldN.value);oR.add("m",oL.iM);oR.send();}
function cbCreatFld(oR){var oL=oR.oCtx;hidFldPrg(oL);if(oR.fST){popLgn();return ;}if(oR.sErr){showErr(oL.all.divFldErr,oR.sErr,oR.sErrDbg);if(oL.all.txtFldN.style.display!="none"){try{setFcs(oL.all.txtFldN);if(oL.all.txtFldN.onfocusout==null)oL.all.txtFldN.onfocusout=onFOFldN;}catch(e){cnFldN(oL);}}return ;}hideErr(oL.all.divFldErr);oL.all.divEnts.innerHTML=oR.sBody;prepSNLEnts(oL);oL.selCur();shwFldN(oL,0);}
function shwFldPrg(oL){if(oL.idCalsPrg)return ;oL.idCalsPrg=window.setTimeout("cbShwFldPrg('"+oL.uniqueID+"')",1000);}
function cbShwFldPrg(sId){var oL=wda(sId);showEm(oL.all.imgFldNPrg);hideEm(oL.all.imgFldNIcn);}
function hidFldPrg(oL){if(oL.idCalsPrg){window.clearTimeout(oL.idCalsPrg);oL.idCalsPrg=0;}hideEm(oL.all.imgFldNPrg);showEm(oL.all.imgFldNIcn);}
function onDOSNFL(){var o=gtSNLEnt(event.srcElement);var oL=gtSNL(o);var oC=gtDrgCtx();if(o&&o.type&&oC&&oC.isVldDrpFld(o.type)){canEvt();aplSNLStl(o,SNLStl.hvr);stDrpEff(0,o._fid);}else {stDrpEff(1);}}
function onDLSNFL(){var o=gtSNLEnt(event.srcElement);if(o){aplSNLStl(o,(gtSNL(o).oSel==o?SNLStl.sel:SNLStl.def));}}
function onDrpSNFL(){var o=gtSNLEnt(event.srcElement);var oL=gtSNL(o);aplSNLStl(o,(oL.oSel==o?SNLStl.sel:SNLStl.def));drpOnFld(o._fid,oL);}
function snflFeOnErr(sMsg,iEC){var oE=new Object();oE.sMsg=sMsg;oE.iEC=iEC;onSNErr(oE);}
function initSNFlt(oF){oF.iCurFlt=null;var rg=items("divFlt",oF);for(var i=0;i<rg.length;i++){if(rg[i].all.inpRdo.checked)oF.iCurFlt=rg[i]._iF;rg[i].onclick=onClkSNFlt;}oF.setFlt=snFltSet;}
function snFltSet(iF){var rg=items("divFlt",this);for(var i=0;i<rg.length;i++){if(rg[i]._iF==iF){chk(rg[i].all.inpRdo);this.iCurFlt=iF;return ;}}}
function onClkSNFlt(){var o=srchPr("divFlt",event.srcElement);var oF=gtSNFlt(o);chk(o.all.inpRdo);oF.iCurFlt=o._iF;eval(oF._onclick);}
function gtSNFlt(o){while(o&&!o.fSNFlt)o=o.parentElement;return o;}
var g_oMbxBtnSt=null;var g_sOpnMbxHtml=null;var L_OpnMbx=null;var L_CnclMbx=null;var L_ErrMbx=null;var L_OpnOtMbx=null;var L_SlctMbx=null;var L_ErrMbxTtl=null;var g_oOpnMbxDlg=null;function opnMbx(){if((opnMbx.fLd&&!g_sOpnMbxHtml)||gtMbxDlg())return ;if(g_sOpnMbxHtml){var y=getCY(spnMbx)+spnMbx.offsetHeight+5;var x=getCX(tdMbxSep)+(g_fRtl?4:-302);g_oOpnMbxDlg=new OpnMbxDlg(onOpnMbxCls);g_oOpnMbxDlg.show(x,y);initMbxRwLnk();}else {opnMbx.fLd=1;var oR=new oeReq("RecipWell","GetOpnMbxRcp",null,cbGetMbxWell);oR.send();}}
opnMbx.fLd=0;function initMbxRwLnk(){divOpnMbxRw.fMbxRw=1;initRw(divOpnMbxRw,1,0,0,onKDMbxRw);divOpnMbxRw.ondragenter=canDrg;divOpnMbxRw.zIdx=g_iDlgZ+2;setFcs(divOpnMbxRw);lnkMbx.style.backgroundColor=getDocBtnSt().backgroundColor;lnkMbx.style.color=getDocBtnSt().color;lnkMbx.style.border="1 solid";lnkMbx.style.borderColor=getDocBtnSt().borderColor;lnkMbx.style.padding=0;imgMbxWd.src=getThmF("dwn.gif");setTimeout(initDlg,1);}
function initDlg(){divOpnMbxUsr.fInit=1;updCmp(window);}
function cbGetMbxWell(oR){if(oR.sErr){shwErrDlg(oR);return ;}var divR=getEm("div");ac(divR);divR.innerHTML=oR.sBody;var oD=divR.all["divMbxCntr"];g_sOpnMbxHtml=oD.innerHTML;L_OpnMbx=oD.L_OpnMbx;L_CnclMbx=oD.L_CnclMbx;L_ErrMbx=oD.L_ErrMbx;L_OpnOtMbx=oD.L_OpnOtMbx;L_SlctMbx=oD.L_SlctMbx;L_ErrMbxTtl=oD.L_ErrMbxTtl;rn(divR);opnMbx();}
function onKDMbxRw(div){var e=event;var iKC=e.keyCode;if(iKC==8||iKC==9||iKC==46||e.ctrlKey||e.altKey)return ;if(errManyRcps()){shwMbxAlrt();return ;}var rgA=getRcpRg(div,RCP_ALL);switch(iKC){case 13:if(rgA[0]>0){anrMbx(1);}else if(rgA[1]>0){window.setTimeout(opnMbxClk,1);}else if(rgA[2]>0){shwMbxAlrt();}break;default:if(rgA[0]>0)return ;else if((rgA[1]>0)||(rgA[2]>0))canEvt();break;}}
function getMbxBtnSt(){if(g_oMbxBtnSt==null)g_oMbxBtnSt=getStyle("mbxLnk");return g_oMbxBtnSt;}
function clsMbxDlg(){onOpnMbxCls();g_oOpnMbxDlg.hide();}
function onOpnMbxCls(){if(g_rgACMs!=null){cclCch();}if(g_fADsp){divOpnMbxRw.fDispDlg=1;divAm.hide();}lnkMbx.style.backgroundColor=lnkMbx.style.borderColor="";lnkMbx.style.color=getMbxBtnSt().color;lnkMbx.style.border=1;lnkMbx.style.padding=1;imgMbxWd.src=getThmF("dn_mblgn.gif");}
function OpnMbxDlg(fnCls){if(!fnCls)fnCls=onOpnMbxCls;var sOppDir=g_fRtl?"left":"right";var sHtml="<div id=divOpnMbxDlg><div class=titlebox>"+"<img class=btn onclick=clsMbxDlg() style=float:"+sOppDir+" src=\""+getThmF("closedlg.gif")+"\">"+L_OpnOtMbx+"</div><div class=mainbox><div class=graybox><table cellpadding=\"0\" cellspacing=\"0\"><tr><td width=\"100%\">"+L_SlctMbx+"</td></tr><tr width=\"100%\"><td id=\"tdMbxRw\" width=\"85%\">"+g_sOpnMbxHtml+"</td><td><div id=divOpnMbx style=\"text-align:"+sOppDir+"\"><button id=btnOpnMbx onclick=\"clkOpnMbxBtn()\" onmouseover=\"btnOnMsOvrBtn(this)\" onmouseout=\"btnOnMsOutBtn(this)\">"+L_OpnMbx+"</button></div></td></tr></table></div></div>";return new Dlg("divOpnMbxUsr",sHtml,0,1,fnCls,0,0);}
function anrMbx(fNav){if(isEmptyMbxRw()||divOpnMbxRw.fAnR)return ;if(chkAndOpnMbx())return ;var f=(btnOpnMbx.innerText==L_OpnMbx);if(f){if(errManyRcps()||ambRcps()){alrt(L_ErrMbx);return ;}btnOpnMbx.innerText=L_CnclMbx;}divOpnMbxRw.fAnR=1;var oC=new Object();oC.fNav=fNav;rslvNms(OP_ANR,divOpnMbxRw.id,cbMbxRslv,oC,1,divOpnMbxRw.zIdx,1);}
function cbMbxRslv(oC,fCncl){if(divOpnMbxRw.fDispDlg)return ;var f=(btnOpnMbx.innerText==L_OpnMbx);if(!oC.fRmv&&!oC.fCan&&!fCncl&&oC.fNav){if(opnMbxClk())return ;}else if(!f){if(!event||!event.toElement||(event.toElement&&(event.toElement.id!="btnOpnMbx"))){btnOpnMbx.innerText=L_OpnMbx;setFcs(divOpnMbxRw);}}divOpnMbxRw.fAnR=0;}
function opnMbxClk(){if(!chkAndOpnMbx()){btnOpnMbx.innerText=L_OpnMbx;setFcs(divOpnMbxRw);return 0;}return 1;}
function chkAndOpnMbx(){var oRcp=lkFstRcp(divOpnMbxRw);if(oRcp&&oRcp.className=="rwRR"){if(oRcp._ao==AO_D){sfWinOpn(window.document.location.protocol+"//"+window.document.location.host+"/owa/"+oRcp._sa);var oR=new oeReq("RecipWell","UpdateAC");var rgPrm=gtUpdAcArry(oR);if(rgPrm!=null&&rgPrm.length!=0){oR.addRgSt("Recips",rgPrm);oR.send();}clsMbxDlg();}else {shwMbxAlrt();}return 1;}return 0;}
function clkOpnMbxBtn(){if(divOpnMbxRw.fAnR)return ;if(isEmptyMbxRw())return ;var f=(btnOpnMbx.innerText==L_OpnMbx);if((f&&errManyRcps())||(f&&ambRcps())){shwMbxAlrt();return ;}btnOpnMbx.innerText=f?L_CnclMbx:L_OpnMbx;if(!f)setFcs(divOpnMbxRw);else anrMbx(1);}
function errManyRcps(){var rgA=getRcpRg(divOpnMbxRw,RCP_ALL);return (rgA&&(rgA[0]+rgA[1]+rgA[2]>1));}
function ambRcps(){var rgA=getRcpRg(divOpnMbxRw,RCP_ALL);return (rgA&&rgA[2]>0);}
function isEmptyMbxRw(){var sU=divOpnMbxRw.innerText.trim();if(sU.length==0){setFcs(divOpnMbxRw);return 1;}return 0;}
function shwMbxAlrt(){var okDlg=new OKDlg(L_ErrMbx,divOpnMbxDlg,onClsMbxAlrt,BDI_WRN,L_ErrMbxTtl);okDlg.show();}
function onClsMbxAlrt(){setFcs(divOpnMbxRw);}
function drpOnFld(sFid,oSN){var o=gtDrgCtx();if(!o)return ;if((o.sDrgT=="items")&&(o.rgItm.length+o.rgCnv.length>MAX_REQ_ITMS)){alrt(L_ErrMaxItms);return ;}var fC=isDrpC(sFid,o);var oCtx=new Object();oCtx.oDC=o;oCtx.fC=fC;oCtx.sDstFId=sFid;oCtx.oSN=oSN;oCtx.oLV=getLstVw(o.sFid);var oR=gtCpMvReq(o,fC,sFid,oCtx,cbDrpF,cbDrpI);oR.send();}
function cbDrpF(oR){var oC=oR.oCtx;var oT=oC.oSN;if(oR.sErr){oT.feOnErr(oR.sErr,oR.oXmlHttp.status);return ;}var oSrc=tryFndTrNd(oC.oDC.sFid);var oDst=tryFndTrNd(oC.sDstFId);if(oDst)gtTr(oDst).cpNdHToF(oR.sBody,oC.sDstFId);if(!oC.fC){if(oSrc){var sSrcId=trGtA(oSrc).sId;if(oT.onBfMvFld)oT.onBfMvFld(sSrcId,oC.sDstFId);var oPS=getNdP(oSrc);oSrc.removeNode(1);if(oPS)updEC(oPS);rmvMd(sSrcId);}}if(oDst)expndNd(oDst);setCSVAsStr(CSV_TR_UPD_DT,new Date());}
function isAllwdELCClss(sT){if(isOfClss(sT,T_MSG)||(sT==T_NTS))return 1;else return 0;}
function pmSetPck(oDp,oMp,fPF){var t=this;t.fPF=fPF;if(fPF){t.oPfDp=oDp;t.oPfMp=oMp;}else {t.oDp=oDp;t.oMp=oMp;}var o=getIF(a_sLstFID);if(o){var fn=o.contentWindow.setPM;if(fn)fn(t);}}
function pmGetDp(){return this.fPF?this.oPfDp:this.oDp;}
function pmGetMp(){return this.fPF?this.oPfMp:this.oMp;}
function pmSetVT(iVT,fPF,fS){var t=this;t.fMV=(iVT==DP_MTH);t.fPF=fPF;t.iMode=t.getDp().iMode=iVT;if(!fS)return ;var o=wda(fPF?"divErrPfDp":"divErrDp");if(o)hideEm(o);var oDp=t.getDp();var oMp=t.getMp();if(!oDp||!oMp)return ;oDp.shw(t.fMV);oMp.shw(!t.fMV);}
function pmSelDs(rgDt){if(this.getDp())this.getDp().setSDs(rgDt);}
function pmSelM(oDt){if(this.getMp())this.getMp().selYM(oDt.gyr(),oDt.gmo()+1,1);}
function pmGetSelDts(){var oP=this.fMV?this.getMp():this.getDp();return oP.getSelDts();}
function PckMgr(){var t=this;t.fPF=t.fMV=t.oPfDp=t.oDp=t.oPfMp=t.oMp=0;t.setPck=pmSetPck;t.getDp=pmGetDp;t.getMp=pmGetMp;t.getSelDts=pmGetSelDts;t.setVT=pmSetVT;t.selDs=pmSelDs;t.selM=pmSelM;}
stJS("unav.js");